#!/usr/bin/python3

# Copyright (C) 2014 Stefano Zacchiroli
# License: GNU General Public License, version 3 or above

# Check Sources.gz file in a given Debian mirror for referenced, but missing,
# files of a source packages; try to guess the proper symlink target from pool.

from __future__ import print_function

import glob
import os
import sys
from pathlib import Path

from debian import deb822


try:
    target_dir = Path(sys.argv[1])
except IndexError:
    target_dir = Path.cwd()
dists_dir = target_dir / 'dists'
pool_dir = target_dir / 'pool'

if not dists_dir.is_dir() or not pool_dir.is_dir():
    print("%s doesn't look like a debian mirror; it should contain dists/ and pool/"
          % target_dir)
    sys.exit(1)


def pkg_prefix(pkg):
    if pkg.startswith('lib'):
        assert len(pkg) >= 4
        return pkg[:4]
    else:
        assert pkg
        return pkg[:1]


def guess_target(path, pool_dir):
    # e.g. path="dists/potato/main/source/games/xsol_0.31-3.1.dsc"
    # to be guessed:    "pool/main/x/xsol/xsol_0.31-3.1.dsc"
    steps = path.parts
    area = steps[2]  # e.g. "main"
    pkg = steps[-1].split('_')[0]  # e.g. "xsol"

    target = Path(pool_dir) / area / pkg_prefix(pkg) / pkg / steps[-1]
    if target.is_file():
        return target
    else:
        return None


os.chdir(target_dir)

for path in glob.glob('dists/*/*/source/Sources.gz'):
    path = Path(path)
    release = path.parts[1]
    if (Path('dists') / release).is_symlink():
        continue  # avoid scanning twice release w/ aliases
    print('scanning %s...' % path, file=sys.stderr)
    with open(path) as index:
        for pkg in deb822.Sources.iter_paragraphs(index):
            src_dir = Path(pkg['directory'])
            for file in pkg['files']:
                src_file = src_dir / file['name']
                if src_file.is_file():
                    dest_file = guess_target(src_file, 'pool')
                    if dest_file:
                        _src_file = src_file.resolve()
                        _dest_file = dest_file.resolve()
                        ln = 'ln -fs %s %s' % \
                             (_dest_file.relative_to(_src_file.parent),
                              _src_file)
                    else:
                        dest_file = ''
                        ln = ''
                    print('missing\t%s\t%s\t%s' % (src_file, dest_file, ln))
